# Generated by Django 5.1.7 on 2025-10-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messengersecret', '0003_create_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_encrypted',
            field=models.BooleanField(default=True),
        ),
    ]
